[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/waitlist"
  to = "/.netlify/functions/orbit-waitlist"
  status = 200

[[redirects]]
  from = "/api/event"
  to = "/.netlify/functions/orbit-event"
  status = 200
